package gate.learningframework;

/*
 *
 */
public enum Algorithm {
	LIBSVM,
	MALLET_CL_C45,
	MALLET_CL_DECISION_TREE,
	MALLET_CL_MAX_ENT,
	MALLET_CL_NAIVE_BAYES_EM,
	MALLET_CL_NAIVE_BAYES,
	MALLET_CL_WINNOW,
	MALLET_SEQ_CRF,
	WEKA_CL_NUM_ADDITIVE_REGRESSION,
	WEKA_CL_NAIVE_BAYES,
	WEKA_CL_J48,
	WEKA_CL_RANDOM_TREE,
	WEKA_CL_IBK
}
